# Generated by Django 4.2.4 on 2023-08-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_amenity_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='description',
        ),
    ]
